### ISSUE TITLE
can you add any preview

### ISSUE THREAD

**Issue by Joseph-Nathan** [Taskulu/material_speed_dial#1]
can you add any preview

**Comment by Amir-P** [comment]
I've updated the README. Check it out for more information. And here is the preview added to README (captured from example project):

![demo](https://user-images.githubusercontent.com/8766492/154555912-e1cadde5-4dc5-44d8-be8c-6058780ad113.gif)

**Comment by Joseph-Nathan** [comment]
thnaks bro.
